const tabela2024 = [
{ nome: 'Botafogo',
    sigla: 'BFR',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Sao Paulo',
    sigla: 'SPFC',
    pontos: 0,
    vitorias: 0,
    empates: 0,             
    golsMarcados: 0,
},
{ nome: 'atletico-PR',
    sigla: 'CAP',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Atletico-MG',
    sigla: 'CAM',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Red Bull Bragantino',
    sigla: 'RBB',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Palmeiras',
    sigla: 'SEP',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Internacional',
    sigla: 'INT',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Fortaleza',
    sigla: 'FCE',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Juventude',
    sigla: 'ECJ',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Gremio',
    sigla: 'GRE',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Cruzeiro',
    sigla: 'CRU',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Vasco',
    sigla: 'CRV',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Corinthians',
    sigla: 'SCCP',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Fluminense',
    sigla: 'FLU',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Criciuma',
    sigla: 'CRI',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Atletico-GO',
    sigla: 'ACG',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Cuiaba',
    sigla: 'CUI',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Vitoria',
    sigla: 'VIT',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
},
{ nome: 'Bahia',
    sigla: 'ECB',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,

},
{
    nome: 'Flamengo',
    sigla: 'FLA',
    pontos: 0,
    vitorias: 0,
    empates: 0,
    golsMarcados: 0,
}
];

export default tabela2024;